package deploy

pipeline {

 agent any
 
    stages {
        stage('Check Java'){
            steps{
                withMaven(options: [artifactsPublisher(disabled: true)], jdk: 'jdk8', maven: 'Maven 3.5') {
                    sh 'mvn -v'
                }
            }
        }
        stage('Clean'){
            steps{
                withMaven(options: [artifactsPublisher(disabled: true)], jdk: 'jdk8', maven: 'Maven 3.5') {
                    sh 'mvn clean'
                }
            }
        }
        stage('packaging back') {
            steps {
                withMaven(options: [artifactsPublisher(disabled: true)], jdk: 'jdk8', maven: 'Maven 3.5') {
                    sh 'mvn install'
                }
            }
        }
        
        stage('Deploy artifact') {
        when{
       	 branch 'master'
        }
            steps {
                withMaven(options: [artifactsPublisher(disabled: true)], jdk: 'jdk8', maven: 'Maven 3.5') {
                    sh 'mvn deploy'
            }
           }
        }
    }
}
